### ISSUE TITLE
Apkg.init creates decks with an empty note

### ISSUE THREAD

**Issue by karlb** [patarapolw/ankisync#1]
When creating new decks with Apkg.init, they always have a single empty note in them. Is this intended, a bug, or am I misunderstanding something? The code I'm using is https://github.com/freedict/tools/blob/master/exporters/tei2anki/tei2anki.py .

**Comment by patarapolw** [comment]
An `*.apkg` without a note is an invalid `*.apkg`, so  I also make a `first_note_data` kwarg.

    @classmethod
    def init(cls,
             first_model: Union[ModelBuilder, dict],
             first_deck: Union[DeckBuilder, str]='Default',
             first_dconf: Union[DConfBuilder, dict]=None,
             first_note_data: Union[bool, dict]=True):

I now allow `first_note_data` to be tagged as `False`.

Please test in your code that I don't break something else during the updating somewhere else in the code.

**Comment by karlb** [comment]
Thanks for the quick feedback! Using `first_note_date=dict(...)` works fine, but `first_note_date=False` causes the following traceback:
```
Traceback (most recent call last):
  File "./tei2anki.py", line 49, in <module>
    first_note_data=False,
  File "/home/karl/code/freedict/venv/lib/python3.5/site-packages/ankisync/anki.py", line 146, in init
    data=first_note_data)
  File "/home/karl/code/freedict/venv/lib/python3.5/site-packages/ankisync/builder/notes.py", line 25, in __init__
    flds.append(str(self.data.get(field_name, '')))
AttributeError: 'bool' object has no attribute 'get'
```

**Comment by patarapolw** [comment]
Have you updated (`pip install -U ankisync`)?

**Comment by karlb** [comment]
Ahh sorry, I missed that you just added that feature. Now it works great. Thanks for the fix!
