### ISSUE TITLE
Anki database structure has changed

### ISSUE THREAD

**Issue by RisingOrange** [patarapolw/ankisync#10]
I don't know which version of Anki introduced these changes. They are also not described here https://github.com/ankidroid/Anki-Android/wiki/Database-Structure. This is just based on my observations of running Anki 2.1.30. I would like to know if others also have observed this changes and in what version of Anki they were introduced / what version of Anki is compatible with AnkiSync.

The five last columns of the Col table (conf, models, decks, dconf, tags) which contained Json data are empty now. Because of this calling methods of the Anki class which access the Col table throw JsonDecodeErrors (e.g. calling Anki.iter_notes()).
The information which was contained in these columns is stored in their own tables now.
conf      -> config
models -> notetypes (the flds are in their own table too - fields)
decks    -> decks
dconf    -> deck_config
tags      -> tags (the table is empty, but notes have tags)

**Comment by patarapolw** [comment]
I see, but there may be nothing I can do.

**Comment by RisingOrange** [comment]
Ok, I found out that the last update to version 2.1.30 of Anki changed the database structure, it is mentioned  under Changes on ankiweb.net (https://changes.ankiweb.net/#/?id=changes-in-2130). 
It broke some implementations in AnkiSync, I will probably attempt rewriting the broken parts to make the project up-to-date.

**Comment by RisingOrange** [comment]
Noticed that there is an anki package on Pypi which can be used to manipulate anki collection files, so this should probably be used for the sort of thing that ankisync does.    Except for the ankiconnect part (because the anki package can't be used while the anki program is running and ankiconnect can). Or maybe ankisync could use the anki package and provide value by having an easier interface to functionality or something.

**Comment by patarapolw** [comment]
> https://pypi.org/project/anki/

Umm, should be safer. But I cannot view the code, nor can I see the documentation for the library.

Still, it is worth looking at the code directly, by all means. (Perhaps, IDE's like VSCode or PyCharm can help with this?)

**Comment by RisingOrange** [comment]
I installed the anki package using pip and it contains the code at https://github.com/ankitects/anki/tree/master/pylib/anki. Then I browsed it using VSCode, the IDE definetely helps with discovering useful functions.

This is a simple usage example:
```
from anki.collection import Collection as Collection
from anki.notes import Note

# create a new collection file
col = Collection(a_file_path)

# create a new deck
foo_deck_id = col.decks.id('FooDeck')

# add note
note = Note(col, col.models.byName('Basic'))
note["Front"] = "1"
note["Back"] = "2"
col.add_note(note, foo_deck_id)

# save the changes to the collection file
col.save()
```

**Comment by patarapolw** [comment]
What is `a_file_path`? Do I need [appdirs](https://pypi.org/project/appdirs/)?

And most importantly, how much is my project currently needed. (I mean this project is very Peewee dependent, not only Python as well.)

**Comment by RisingOrange** [comment]
```a_file_path``` is a path to where a new collection file will be created. To change the exisiting collection file which Anki knows the location of, appdirs would be needed.

Honestly I think that ankisync is not needed much right now, except for the ankiconnect part. I would just use anki directly instead, but I could be wrong.

**Comment by patarapolw** [comment]
So, I have download and looked into how Anki 2.1 works.

Maybe I should update [ankisync2](https://github.com/patarapolw/ankisync2), to prevent breaking changes in the more popular repo. here.

https://github.com/patarapolw/ankisync2/issues/3

**Comment by patarapolw** [comment]
@RisingOrange 

I tried [editing the database](https://github.com/patarapolw/ankisync2/blob/master/scripts/clean_user_data.py) with [new models for newer Anki versions](https://github.com/patarapolw/ankisync2/blob/master/ankisync2/anki21/db.py).

It may break something, though. Always back up.

**Comment by patarapolw** [comment]
See https://github.com/patarapolw/ankisync2/tree/master/anki2.1.26
