### ISSUE TITLE
Please tell the state of your old project on pypi

### ISSUE THREAD

**Issue by guettli** [patarapolw/ankisync#11]
Hi,

Thank you for your anki libraries.

Please tell us the state of your old project here: https://pypi.org/project/AnkiTools/#description

This helps to waste less time.

Thank you.

**Comment by patarapolw** [comment]
Do you if there is a an easy web to mark as deprecated? Don't have to touch even README.md

**Comment by guettli** [comment]
Good question! I will ask the pypi people.

**Comment by guettli** [comment]
@patarapolw 

PiPy folks suggest:

> Maybe the trove classifier Development Status :: 7 - Inactive ?

**Comment by patarapolw** [comment]
More of the linked issue, that is still open. - https://github.com/pypa/warehouse/issues/345

Anyway, updated the state for now.
