### ISSUE TITLE
anki_convert()

### ISSUE THREAD

**Issue by guettli** [patarapolw/ankisync#12]
I looked at your old project and found this:

```
>>> from AnkiTools import anki_convert
>>> anki_convert('Chinese.apkg', out_file='Chinese_anki.xlsx')
```

This was exactly what I was looking for.

How can I do this with ankisync?

**Comment by patarapolw** [comment]
Ankisync is just peewee ORM to interact with `*.apkg`. Nonetheless, you can just copy the code from AnkiTools, and run SQL directly.

**Comment by guettli** [comment]
Thank you for your answer.
