### ISSUE TITLE
a.update_note_fields() doesn't make persistent changes

### ISSUE THREAD

**Issue by mvanaltvorst** [patarapolw/ankisync#4]
```
with Apkg("./test.apkg") as deck1:
    for note in deck1.iter_notes():
        print(note)
        deck1.update_note_fields(note_id=note["_nid"], fields={"Text": "asdf"})
```

This prints every note in an .apkg and updates the `text` field with `asdf`. When running this a second time, the Text fields don't appear to be updated. I've confirmed this by importing the deck into Anki, all the Text fields are still their original values. What is going wrong?

**Comment by patarapolw** [comment]
Is it a new field? I seem to haven't add a functionality for that yet.

Seems to be ORM problem. `Notes.save()` returns zero. I cannot fix.

**Comment by patarapolw** [comment]
ORM's fault. Solved via workaround.
