### ISSUE TITLE
Adding notes to existing apkg and maintain progress

### ISSUE THREAD

**Issue by hsab** [patarapolw/ankisync#5]
Thank you for the wonderful library. It has really eased some tedious processes.
I was wondering if it's possible to add to an existing apkg while maintaining the progress inside the app, without losing the stats for reviews, etc.

Thank you in advance

**Comment by patarapolw** [comment]
@hsab You can unzip and `*.apkg` to get `*.anki2` and `media`, and edit, then zip back, to see if it works.

**Comment by patarapolw** [comment]
Should be possible with https://github.com/patarapolw/ankisync2
