### ISSUE TITLE
get_collection_path does not work on Windows

### ISSUE THREAD

**Issue by RisingOrange** [patarapolw/ankisync#8]
To make the function get the actual path on my machine, I had to change the code at https://github.com/patarapolw/ankisync/blob/aa5f2df6daa0e5a026196e0a0c4135febeef2159/ankisync/dir.py#L9 from:
`collection_path = os.path.join(appdirs.user_data_dir('Anki2'), account_name, 'collection.anki2')`

to:
`collection_path = os.path.join(appdirs.user_data_dir('Anki2', appauthor=False, roaming=True), account_name, 'collection.anki2')`

The first of the two generates the (wrong) path "C:\Users\username\AppData\Local\Anki2\Anki2\User 1\collection.anki2",
the second "C:\Users\username\AppData\Roaming\Anki2\User 1\collection.anki2".

**Comment by patarapolw** [comment]
Thanks. Please make a PR.

Not sure about cross-OS testing. Maybe some kinds of CI?

**Comment by RisingOrange** [comment]
Created the PR. Don't know how to do the cross-OS testing unfortunately.

**Comment by patarapolw** [comment]
Your solution seems to be correct for macOS and Linux as well. Updated accordingly.
